/** @type {import('tailwindcss').Config} */
export default {
  
 content: [
    "./index.html",
    "./video-production-portfolio.html",
    "./creative-video-productions.html",
    "./charity-video-production.html",
    "./nature-video-production.html",
    "./blog.html",
    "./video-content-packages.html",
    "./contact.html",
    "./african-bat-conservation-munjiri-videos.html",
    "./brand-story-video-guide.html",
    "./brand-video-production.html",
    "./brand-videos.html",
    "./charity-videographer.html",
    "./charleston-house.html",
    "./coimbra-video-production.html",
    "./collingwood-norris-knitwear-munjiri-videos.html",
    "./common-mistakes-social-media-video-production.html",
    "./dehye-collective-cape-town.html",
    "./drone-videographer-portugal.html",
    "./drone-videographer.html",
    "./editor-videographer.html",
    "./event-video-production.html",
    "./how-to-be-more-confident-on-camera.html",
    "./how-to-create-a-storytelling-video.html",
    "./how-to-optimize-youtube-videos-for-seo.html",
    "./how-to-plan-successful-video-content.html",
    "./how-to-tell-an-engaging-video-story.html",
    "./kate-ray-guided-wellbeing.html",
    "./kew-gardens-palm-house.html",
    "./kgalagadi-national-park-travel-guide.html",
    "./learn-video-making.html",
    "./lisbon-videographer.html",
    "./make-storytelling-video.html",
    "./mayamiko-a-meaningful-wardrobe.html",
    "./natasha-minyon-sale-the-adorned.html",
    "./nyika-national-park-travel-guide.html",
    "./picking-damsons-jam-recipe.html",
    "./product-video-production.html",
    "./social-media-video-production.html",
    "./social-media-for-charity.html",
    "./social-media-video-ideas.html",
    "./social-media-video-production.html",
    "./social-media-videography.html",
    "./soul-design-jewellery-munjiri-videos.html",
    "./sour-fig-jam-recipe.html",
    "./sustainable-video-production.html",
    "./the-best-way-to-upload-video-on-youtube.html",
    "./travel-video-production.html",
    "./uk-videographer.html",
    "./video-advice-composition.html",
    "./video-advice-natural-light.html",
    "./video-production-cape-town.html",
    "./video-production-for-non-profit-questions.html",
    "./video-production-for-sustainable-brands.html",
    "./video-production-kenya.html",
    "./video-production-portugal.html",
    "./video-production-south-africa.html",
    "./videographer-portugal-cost.html",
    "./videographer-portugal.html",
    "./videographer-south-africa.html",
    "./wandering-the-cederberg.html",
    "./wedding-videographer-portugal.html",
    "./why-charities-need-videography.html",
    "./why-is-video-marketing-effective.html",
    "./wildlife-videography.html",
    "./woman-videographer.html",
    "./yoga-videographer.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        linen: 'rgb(254, 252, 250)',
      },
      fontFamily: {
        crimson: ['"Crimson Text"', 'serif'],
      },
    },
  },
  plugins: [],
}
