/** @type {import('tailwindcss').Config} */
export default {
  
 content: [
    "./index.html",
    "./video-production-portfolio.html",
    "./creative-videographer.html",
    "./charity-videographer.html",
    "./nature-videographer.html",
    "./blog.html",
    "./video-content-packages.html",
    "./contact.html",
    "./african-bat-conservation-munjiri-videos.html",
    "./brand-videographer.html",
    "./charity-videographer.html",
    "./charleston-house.html",
    "./coimbra-videographer.html",
    "./collingwood-norris-knitwear-munjiri-videos.html",
    "./common-mistakes-social-media-video-production.html",
    "./dehye-collective-cape-town.html",
    "./drone-videographer-portugal.html",
    "./drone-videographer.html",
    "./editor-videographer.html",
    "./event-videographer.html",
    "./how-to-be-more-confident-on-camera.html",
    "./kate-ray-guided-wellbeing.html",
    "./kew-gardens-palm-house.html",
    "./learn-video-making.html",
    "./lisbon-videographer.html",
    "./locations.html",
    "./mayamiko-a-meaningful-wardrobe.html",
    "./natasha-minyon-sale-the-adorned.html",
    "./nyika-national-park-travel-guide.html",
    "./picking-damsons-jam-recipe.html",
    "./product-videographer.html",
    "./social-media-video-ideas.html",
    "./social-media-videographer.html",
    "./soul-design-jewellery-munjiri-videos.html",
    "./sour-fig-jam-recipe.html",
    "./the-best-way-to-upload-video-on-youtube.html",
    "./travel-videographer.html",
    "./uk-videographer.html",
    "./video-advice-composition.html",
    "./video-advice-natural-light.html",
    "./videographer-cape-town.html",
    "./videographer-kenya.html",
    "./videographer-portugal-cost.html",
    "./videographer-portugal.html",
    "./videographer-south-africa.html",
    "./videographer",
    "./wandering-the-cederberg.html",
    "./wedding-videographer-portugal.html",
    "./woman-videographer.html",
    "./yoga-videographer.html",
    "./src/**/*.{js,ts,jsx,tsx}"
  ],
  theme: {
    extend: {
      colors: {
        linen: 'rgb(254, 252, 250)',
      },
      fontFamily: {
        crimson: ['"Crimson Text"', 'serif'],
      },
    },
  },
  plugins: [],
}
