import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  base: '/',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        portfolio: path.resolve(__dirname, 'video-production-portfolio.html'),
        creativevideoproductions: path.resolve(__dirname, 'creative-video-productions.html'),
        charityvideoproduction: path.resolve(__dirname, 'charity-video-production.html'),
        naturevideoproduction: path.resolve(__dirname, 'nature-video-production.html'),
        blog: path.resolve(__dirname, 'blog.html'),
        services: path.resolve(__dirname, 'video-content-packages.html'),
        contact: path.resolve(__dirname, 'contact.html'),
        africanbatconservationmunjirivideos: path.resolve(__dirname, 'african-bat-conservation-munjiri-videos.html'),
        brandstoryvideoguide: path.resolve(__dirname, 'brand-story-video-guide.html'),
        brandvideoproduction: path.resolve(__dirname, 'brand-video-production.html'),
        brandvideos: path.resolve(__dirname, 'brand-videos.html'),
        charityvideographer: path.resolve(__dirname, 'charity-videographer.html'),
        charlestonhouse: path.resolve(__dirname, 'charleston-house.html'),
        coimbravideoproduction: path.resolve(__dirname, 'coimbra-video-production.html'),
        collingwoodnorrisknitwearmunjirivideos: path.resolve(__dirname, 'collingwood-norris-knitwear-munjiri-videos.html'),
        commonmistakessocialmediavideoproduction: path.resolve(__dirname, 'common-mistakes-social-media-video-production.html'),
        dehyecollectivecapetown: path.resolve(__dirname, 'dehye-collective-cape-town.html'),
        dronevideographerportugal: path.resolve(__dirname, 'drone-videographer-portugal.html'),
        dronevideographer: path.resolve(__dirname, 'drone-videographer.html'),
        editorvideographer: path.resolve(__dirname, 'editor-videographer.html'),
        eventvideoproduction: path.resolve(__dirname, 'event-video-production.html'),
        howtobemoreconfidentoncamera: path.resolve(__dirname, 'how-to-be-more-confident-on-camera.html'),
        howtocreateastorytellingvideo: path.resolve(__dirname, 'how-to-create-a-storytelling-video.html'),
        howtooptimizeyoutubevideosforseo: path.resolve(__dirname, 'how-to-optimize-youtube-videos-for-seo.html'),
        howtoplansuccessfulvideocontent: path.resolve(__dirname, 'how-to-plan-successful-video-content.html'),
        howtotellanengagingvideostory: path.resolve(__dirname, 'how-to-tell-an-engaging-video-story.html'),
        katerayguidedwellbeing: path.resolve(__dirname, 'kate-ray-guided-wellbeing.html'),
        kewgardenspalmhouse: path.resolve(__dirname, 'kew-gardens-palm-house.html'),
        kgalagadinationalparktravelguide: path.resolve(__dirname, 'kgalagadi-national-park-travel-guide.html'),
        learnvideomaking: path.resolve(__dirname, 'learn-video-making.html'),
        lisbonvideographer: path.resolve(__dirname, 'lisbon-videographer.html'),
        makestorytellingvideo: path.resolve(__dirname, 'make-storytelling-video.html'),
        mayamikoameaningfulwardrobe: path.resolve(__dirname, 'mayamiko-a-meaningful-wardrobe.html'),
        natashaminyonsaletheadorned: path.resolve(__dirname, 'natasha-minyon-sale-the-adorned.html'),
        nyikanationalparktravelguide: path.resolve(__dirname, 'nyika-national-park-travel-guide.html'),
        pickingdamsonsjamrecipe: path.resolve(__dirname, 'picking-damsons-jam-recipe.html'),
        productvideoproduction: path.resolve(__dirname, 'product-video-production.html'),
        socialmediavideoproduction: path.resolve(__dirname, 'social-media-video-production.html'),
        socialmediaforcharity: path.resolve(__dirname, 'social-media-for-charity.html'),
        socialmediavideoideas: path.resolve(__dirname, 'social-media-video-ideas.html'),
        socialmediavideoproduction: path.resolve(__dirname, 'social-media-video-production.html'),
        socialmediavideography: path.resolve(__dirname, 'social-media-videography.html'),
        souldesignjewellerymunjirivideos: path.resolve(__dirname, 'soul-design-jewellery-munjiri-videos.html'),
        sourfigjamrecipe: path.resolve(__dirname, 'sour-fig-jam-recipe.html'),
        sustainablevideoproduction: path.resolve(__dirname, 'sustainable-video-production.html'),
        thebestwaytouploadvideoonyoutube: path.resolve(__dirname, 'the-best-way-to-upload-video-on-youtube.html'),
        travelvideoproduction: path.resolve(__dirname, 'travel-video-production.html'),
        ukvideographer: path.resolve(__dirname, 'uk-videographer.html'),
        videoadvicecomposition: path.resolve(__dirname, 'video-advice-composition.html'),
        videoadvicenaturallight: path.resolve(__dirname, 'video-advice-natural-light.html'),
        videoproductioncapetown: path.resolve(__dirname, 'video-production-cape-town.html'),
        videoproductionfornonprofitquestions: path.resolve(__dirname, 'video-production-for-non-profit-questions.html'),
        videoproductionforsustainablebrands: path.resolve(__dirname, 'video-production-for-sustainable-brands.html'),
        videoproductionkenya: path.resolve(__dirname, 'video-production-kenya.html'),
        videoproductionportugal: path.resolve(__dirname, 'video-production-portugal.html'),
        videoproductionsouthafrica: path.resolve(__dirname, 'video-production-south-africa.html'),
        videographerportugalcost: path.resolve(__dirname, 'videographer-portugal-cost.html'),
        videographerportugal: path.resolve(__dirname, 'videographer-portugal.html'),
        videographersouthafrica: path.resolve(__dirname, 'videographer-south-africa.html'),
        wanderingthecederberg: path.resolve(__dirname, 'wandering-the-cederberg.html'),
        weddingvideographerportugal: path.resolve(__dirname, 'wedding-videographer-portugal.html'),
        whycharitiesneedvideography: path.resolve(__dirname, 'why-charities-need-videography.html'),
        whyisvideomarketingeffective: path.resolve(__dirname, 'why-is-video-marketing-effective.html'),
        wildlifevideography: path.resolve(__dirname, 'wildlife-videography.html'),
        womanvideographer: path.resolve(__dirname, 'woman-videographer.html'),
        yogavideographer: path.resolve(__dirname, 'yoga-videographer.html'),
      }
    }
  }
})
