import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  base: '/',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        portfolio: path.resolve(__dirname, 'video-production-portfolio.html'),
        creativevideoproductions: path.resolve(__dirname, 'creative-videographer.html'),
        charityvideoproduction: path.resolve(__dirname, 'charity-videographer.html'),
        naturevideoproduction: path.resolve(__dirname, 'nature-videographer.html'),
        blog: path.resolve(__dirname, 'blog.html'),
        services: path.resolve(__dirname, 'video-content-packages.html'),
        contact: path.resolve(__dirname, 'contact.html'),
        africanbatconservationmunjirivideos: path.resolve(__dirname, 'african-bat-conservation-munjiri-videos.html'),
        brandvideoproduction: path.resolve(__dirname, 'brand-videographer.html'),
        charityvideographer: path.resolve(__dirname, 'charity-videographer.html'),
        charlestonhouse: path.resolve(__dirname, 'charleston-house.html'),
        coimbravideoproduction: path.resolve(__dirname, 'coimbra-videographer.html'),
        collingwoodnorrisknitwearmunjirivideos: path.resolve(__dirname, 'collingwood-norris-knitwear-munjiri-videos.html'),
        commonmistakessocialmediavideoproduction: path.resolve(__dirname, 'common-mistakes-social-media-video-production.html'),
        dehyecollectivecapetown: path.resolve(__dirname, 'dehye-collective-cape-town.html'),
        dronevideographerportugal: path.resolve(__dirname, 'drone-videographer-portugal.html'),
        dronevideographer: path.resolve(__dirname, 'drone-videographer.html'),
        editorvideographer: path.resolve(__dirname, 'editor-videographer.html'),
        eventvideoproduction: path.resolve(__dirname, 'event-videographer.html'),
        howtobemoreconfidentoncamera: path.resolve(__dirname, 'how-to-be-more-confident-on-camera.html'),
        katerayguidedwellbeing: path.resolve(__dirname, 'kate-ray-guided-wellbeing.html'),
        kewgardenspalmhouse: path.resolve(__dirname, 'kew-gardens-palm-house.html'),
        learnvideomaking: path.resolve(__dirname, 'learn-video-making.html'),
        lisbonvideographer: path.resolve(__dirname, 'lisbon-videographer.html'),
        locations: path.resolve(__dirname, 'locations.html'),
        mayamikoameaningfulwardrobe: path.resolve(__dirname, 'mayamiko-a-meaningful-wardrobe.html'),
        natashaminyonsaletheadorned: path.resolve(__dirname, 'natasha-minyon-sale-the-adorned.html'),
        nyikanationalparktravelguide: path.resolve(__dirname, 'nyika-national-park-travel-guide.html'),
        pickingdamsonsjamrecipe: path.resolve(__dirname, 'picking-damsons-jam-recipe.html'),
        productvideoproduction: path.resolve(__dirname, 'product-videographer.html'),
        socialmediavideoideas: path.resolve(__dirname, 'social-media-video-ideas.html'),
        socialmediavideography: path.resolve(__dirname, 'social-media-videographer.html'),
        souldesignjewellerymunjirivideos: path.resolve(__dirname, 'soul-design-jewellery-munjiri-videos.html'),
        sourfigjamrecipe: path.resolve(__dirname, 'sour-fig-jam-recipe.html'),
        thebestwaytouploadvideoonyoutube: path.resolve(__dirname, 'the-best-way-to-upload-video-on-youtube.html'),
        travelvideoproduction: path.resolve(__dirname, 'travel-videographer.html'),
        ukvideographer: path.resolve(__dirname, 'uk-videographer.html'),
        videoadvicecomposition: path.resolve(__dirname, 'video-advice-composition.html'),
        videoadvicenaturallight: path.resolve(__dirname, 'video-advice-natural-light.html'),
        videoproductioncapetown: path.resolve(__dirname, 'videographer-cape-town.html'),
        videoproductionkenya: path.resolve(__dirname, 'videographer-kenya.html'),
        videographerportugalcost: path.resolve(__dirname, 'videographer-portugal-cost.html'),
        videographerportugal: path.resolve(__dirname, 'videographer-portugal.html'),
        videographersouthafrica: path.resolve(__dirname, 'videographer-south-africa.html'),
        videographer: path.resolve(__dirname, 'videographer.html'),
        wanderingthecederberg: path.resolve(__dirname, 'wandering-the-cederberg.html'),
        weddingvideographerportugal: path.resolve(__dirname, 'wedding-videographer-portugal.html'),
        womanvideographer: path.resolve(__dirname, 'woman-videographer.html'),
        yogavideographer: path.resolve(__dirname, 'yoga-videographer.html'),
      }
    }
  }
})
