import { defineConfig } from 'vite'
import path from 'path'

export default defineConfig({
  base: '/',
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        main: path.resolve(__dirname, 'index.html'),
        about: path.resolve(__dirname, 'about/index.html'),
        blog: path.resolve(__dirname, 'blog/index.html'),
        fieldnotes: path.resolve(__dirname, 'blog/field-notes/index.html'),
        behindthescenesvideographysouthafrica: path.resolve(__dirname, 'blog/field-notes/behind-the-scenes-videography-south-africa/index.html'),
        nyikanationalparktravelguide: path.resolve(__dirname, 'blog/field-notes/nyika-national-park-travel-guide/index.html'),
        pickingdamsonsjamrecipe: path.resolve(__dirname, 'blog/field-notes/picking-damsons-jam-recipe/index.html'),
        wanderingthecederberg: path.resolve(__dirname, 'blog/field-notes/wandering-the-cederberg/index.html'),
        questionstoaskavideographerportugal: path.resolve(__dirname, 'blog/questions-to-ask-a-videographer-portugal/index.html'),
        skills: path.resolve(__dirname, 'blog/skills/index.html'),
        howtobemoreconfidentoncamera: path.resolve(__dirname, 'blog/skills/how-to-be-more-confident-on-camera/index.html'),
        howtoeditvideosforsocialmedia: path.resolve(__dirname, 'blog/skills/how-to-edit-videos-for-social-media/index.html'),
        videoadvicecomposition: path.resolve(__dirname, 'blog/skills/video-advice-composition/index.html'),
        videoadvicenaturallight: path.resolve(__dirname, 'blog/skills/video-advice-natural-light/index.html'),
        strategy: path.resolve(__dirname, 'blog/strategy/index.html'),
        commonmistakessocialmediavideoproduction: path.resolve(__dirname, 'blog/strategy/common-mistakes-social-media-video-production/index.html'),
        socialmediavideoideas: path.resolve(__dirname, 'blog/strategy/social-media-video-ideas/index.html'),
        thebestwaytouploadvideoonyoutube: path.resolve(__dirname, 'blog/strategy/the-best-way-to-upload-video-on-youtube/index.html'),
        videostorytelling: path.resolve(__dirname, 'blog/strategy/video-storytelling/index.html'),
        contact: path.resolve(__dirname, 'contact/index.html'),
        learn: path.resolve(__dirname, 'learn/index.html'),
        learnvideomaking: path.resolve(__dirname, 'learn/learn-video-making/index.html'),
        locations: path.resolve(__dirname, 'locations/index.html'),
        videoproductionkenya: path.resolve(__dirname, 'locations/kenya/index.html'),
        videographerportugal: path.resolve(__dirname, 'locations/portugal/index.html'),
        videographercoimbra: path.resolve(__dirname, 'locations/portugal/coimbra/index.html'),
        videographerlisbon: path.resolve(__dirname, 'locations/portugal/lisbon/index.html'),
        videographerporto: path.resolve(__dirname, 'locations/portugal/porto/index.html'),
        videographersouthafrica: path.resolve(__dirname, 'locations/south-africa/index.html'),
        videographercapetown: path.resolve(__dirname, 'locations/south-africa/cape-town/index.html'),
        videographeruk: path.resolve(__dirname, 'locations/uk/index.html'),
        videographerlondon: path.resolve(__dirname, 'locations/uk/london/index.html'),
        portfolio: path.resolve(__dirname, 'portfolio/index.html'),
        africanbatconservation: path.resolve(__dirname, 'portfolio/african-bat-conservation/index.html'),
        charlestonhouse: path.resolve(__dirname, 'portfolio/charleston-house/index.html'),
        collingwoodnorrisknitwearmunjirivideos: path.resolve(__dirname, 'portfolio/collingwood-norris-knitwear/index.html'),
        evelynbertrand: path.resolve(__dirname, 'portfolio/evelyn-bertrand/index.html'),
        katerayguidedwellbeing: path.resolve(__dirname, 'portfolio/kate-ray-guided-wellbeing/index.html'),
        kewgardenspalmhouse: path.resolve(__dirname, 'portfolio/kew-gardens-palm-house/index.html'),
        mayamikoameaningfulwardrobe: path.resolve(__dirname, 'portfolio/mayamiko-a-meaningful-wardrobe/index.html'),
        natashaminyonsaletheadorned: path.resolve(__dirname, 'portfolio/natasha-minyon-sale-the-adorned/index.html'),
        souldesignjewellery: path.resolve(__dirname, 'portfolio/soul-design-jewellery/index.html'),
        sourfigjamrecipe: path.resolve(__dirname, 'portfolio/sour-fig-jam-recipe/index.html'),
        services: path.resolve(__dirname, 'services/index.html'),
        brandvideoproduction: path.resolve(__dirname, 'services/brand-videographer/index.html'),
        charityvideographer: path.resolve(__dirname, 'services/charity-videographer/index.html'),
        dronevideographer: path.resolve(__dirname, 'services/drone-videographer/index.html'),
        socialmediavideograper: path.resolve(__dirname, 'services/social-media-videographer/index.html'),
        travelvideographer: path.resolve(__dirname, 'services/travel-videographer/index.html'),
        womanvideographer: path.resolve(__dirname, 'services/woman-videographer/index.html'),
      }
    }
  }
})
